# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.__version__)

1.26.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [13]:
### [your code here]
a = np.random.rand(2, 3, 5)
 



### 4. Print a.


In [14]:
### [your code here]
print(a)

[[[0.3708426  0.21860075 0.32313027 0.28420977 0.04576059]
  [0.3014287  0.13774354 0.42254551 0.10617289 0.16873202]
  [0.70987239 0.86429394 0.56677266 0.85634914 0.82315762]]

 [[0.50215447 0.40153917 0.28973023 0.89541061 0.16942789]
  [0.04553678 0.89085109 0.71639827 0.99961147 0.0509936 ]
  [0.43080419 0.75158439 0.39489152 0.50105907 0.23638647]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [16]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [17]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [21]:
### [your code here]
print(a.size)
print(b.size)

the_same_size = b.size == a.size

print(the_same_size)


30
30
True



### 8. Are you able to add a and b? Why or why not?


In [24]:
### [your code here]
#adition_of_a_and_b = a + b
#print(adition_of_a_and_b)
 
# they can nt be added because they are not the same shape a = 2,3,5 b = 5,2,3 

# they potentioal could be added togetehr even if they do not have the same shape if either 
# #a and b has only 1 diemnsion ex a = 1,3,5 and b = 5,2,3 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [39]:
### [your code here]5x2x3
c = np.transpose(b, [1, 2, 0])
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a + c
display(d)

# this time adding a and c works because both of them have the same shape 
#since we store a trasformed version of b in c that matches the shape of a


array([[[1.3708426 , 1.21860075, 1.32313027, 1.28420977, 1.04576059],
        [1.3014287 , 1.13774354, 1.42254551, 1.10617289, 1.16873202],
        [1.70987239, 1.86429394, 1.56677266, 1.85634914, 1.82315762]],

       [[1.50215447, 1.40153917, 1.28973023, 1.89541061, 1.16942789],
        [1.04553678, 1.89085109, 1.71639827, 1.99961147, 1.0509936 ],
        [1.43080419, 1.75158439, 1.39489152, 1.50105907, 1.23638647]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [44]:
### [your code here]
print("--- Array a ---")
print(a)
print("\n--- Array d ---")
print(d)

# The relation between 'a' and 'd' is that every single value in 'd' is exactly 1 unit greater than the corresponding value in 'a' (d = a + 1). 
# This happens because 'c' was an array entirely composed of 1s, and NumPy performed an element-wise addition between 'a' and 'c'.



--- Array a ---
[[[0.3708426  0.21860075 0.32313027 0.28420977 0.04576059]
  [0.3014287  0.13774354 0.42254551 0.10617289 0.16873202]
  [0.70987239 0.86429394 0.56677266 0.85634914 0.82315762]]

 [[0.50215447 0.40153917 0.28973023 0.89541061 0.16942789]
  [0.04553678 0.89085109 0.71639827 0.99961147 0.0509936 ]
  [0.43080419 0.75158439 0.39489152 0.50105907 0.23638647]]]

--- Array d ---
[[[1.3708426  1.21860075 1.32313027 1.28420977 1.04576059]
  [1.3014287  1.13774354 1.42254551 1.10617289 1.16873202]
  [1.70987239 1.86429394 1.56677266 1.85634914 1.82315762]]

 [[1.50215447 1.40153917 1.28973023 1.89541061 1.16942789]
  [1.04553678 1.89085109 1.71639827 1.99961147 1.0509936 ]
  [1.43080419 1.75158439 1.39489152 1.50105907 1.23638647]]]



### 12. Multiply a and c. Assign the result to e.


In [48]:
### [your code here]

e = a * c
display(e)

array([[[0.3708426 , 0.21860075, 0.32313027, 0.28420977, 0.04576059],
        [0.3014287 , 0.13774354, 0.42254551, 0.10617289, 0.16873202],
        [0.70987239, 0.86429394, 0.56677266, 0.85634914, 0.82315762]],

       [[0.50215447, 0.40153917, 0.28973023, 0.89541061, 0.16942789],
        [0.04553678, 0.89085109, 0.71639827, 0.99961147, 0.0509936 ],
        [0.43080419, 0.75158439, 0.39489152, 0.50105907, 0.23638647]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
verification = a == e
print(verification)
 
# yes a and e are equal because we are multipling a by c which is compose by 1s



[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [53]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)


1.9996114715075897
1.0455367837217062
1.4491997212699081



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [59]:
### [your code here]
f = np.empty_like(d)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [60]:
### [your code here]
for i in range(2):        # Bloques
    for j in range(3):    # Filas
        for k in range(5): # Columnas
            
            d_value = d[i, j, k]
            if d_value == d_min:
                f[i, j, k] = 0
            elif d_min < d_value < d_mean:
                f[i, j, k] = 25
            elif d_value == d_mean:
                f[i, j, k] = 50
            elif d_mean < d_value < d_max:
                f[i, j, k] = 75
            elif d_value == d_max:
                f[i, j, k] = 100

print(f)


[[[ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  75.  75. 100.  25.]
  [ 25.  75.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [61]:
### [your code here]
print(d)
print(f)

[[[1.3708426  1.21860075 1.32313027 1.28420977 1.04576059]
  [1.3014287  1.13774354 1.42254551 1.10617289 1.16873202]
  [1.70987239 1.86429394 1.56677266 1.85634914 1.82315762]]

 [[1.50215447 1.40153917 1.28973023 1.89541061 1.16942789]
  [1.04553678 1.89085109 1.71639827 1.99961147 1.0509936 ]
  [1.43080419 1.75158439 1.39489152 1.50105907 1.23638647]]]
[[[ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  75.  75. 100.  25.]
  [ 25.  75.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]